### ISSUE TITLE
numberWithObject leaks memory

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/NSObject-SafeExpectations#2]
I'm not entirely sure it's anything we have direct control over, but it looks like numberWithObject is leaky.

![2014-04-22_09-45-25](https://cloud.githubusercontent.com/assets/373903/2766225/bf11431a-ca2c-11e3-8503-038ca13c4482.png)

If anything, I'd suggest a class check before alloc/initing an NSNumberFormatter object to short circuit the return if the object is already an NSNumber.

**Comment by astralbodies** [comment]
@koke This one has been hanging around for a while along with the 1.0 release. Kill?

**Comment by koke** [comment]
Yeah. I've been thinking we should abandon this pod and just have some helpers in our XML-RPC client.
